name: GEMA-OPERASI-CUAN-V1
on: [push, workflow_dispatch]
jobs:
  eksekusi_intelijen:
    runs-on: ubuntu-latest
    steps:
      - name: "Ambil Kode PT GEMA"
        uses: actions/checkout@v4

      - name: "Jalankan Otak Pencari Cuan"
        run: python otak_gema_ai.py

